// Danh sách câu hỏi phân loại theo nhóm/chủ đề
const questions = [
    // ==========================================
    // 🌸 NHÓM: GAME HOA VIÊN
    // ==========================================
    { category: "Game Hoa Viên", q: "Thiên Cung là hoa phẩm gì ?", a: "Đỏ" },
    { category: "Game Hoa Viên", q: "Vạn Tuế Lá Xanh trị giá bao nhiu xu ?", a: "3880" },
    { category: "Game Hoa Viên", q: "Ghim Cài lửa trị giá bao nhiu xu ?", a: "3880" },
    { category: "Game Hoa Viên", q: "Hoa Lộ Vi Vàng trị giá bao nhiu xu?", a: "4880" },
    { category: "Game Hoa Viên", q: "Hồng Môn Phấn bao nhiu xu ?", a: "7880" },
    { category: "Game Hoa Viên", q: "Vạn Tuế Lá Lam bao nhiu xu?", a: "11800" },
    { category: "Game Hoa Viên", q: "Mỹ Nhụy Răng Cưa cắm cho bình nào?", a: "Bình Việt Nam" },
    { category: "Game Hoa Viên", q: "Linh Lan cắm bình nào ?", a: "Bình Việt Nam" },
    { category: "Game Hoa Viên", q: "Tử La Lan cắm bình nào ?", a: "Nét Sứ Bách Hợp" },
    { category: "Game Hoa Viên", q: "Lan Hoàng Thảo Tím Dịu cắm bình nào?", a: "Trăng Lặn Sao Rơi" },
    { category: "Game Hoa Viên", q: "Tối đa bán được bao nhiu bình hoa nghệ thuật 1 lần ?", a: "72" },
    { category: "Game Hoa Viên", q: "1 ngày tối đa bán được bao nhiu đơn vải lụa ?", a: "120" },
    { category: "Game Hoa Viên", q: "Tối đa bán được bao nhiu bình hoa nghệ thuật 1 ô ?", a: "12" },
    { category: "Game Hoa Viên", q: "1 ngày tối đa bán được bao nhiu đơn vật liệu xây dựng ?", a: "120" },
    { category: "Game Hoa Viên", q: "1 Ngày thu hoạch được tối đa bao nhiu xô nước ?", a: "60" },
    { category: "Game Hoa Viên", q: "1 ngày tối đa xem quảng cáo tăng tốc được bao nhiu lần ?", a: "6" },
    { category: "Game Hoa Viên", q: "Chợ hoa bán 1 lần tối đa được bao nhiu ô ?", a: "9" },
    { category: "Game Hoa Viên", q: "Ở chợ hoa bán tối đa bao nhiu bông cho 1 ô ?", a: "25" },
    { category: "Game Hoa Viên", q: "Hội hạng A làm tối đa được bao nhiu nhiệm vụ đua thuyền miễn phí ?", a: "18" },
    { category: "Game Hoa Viên", q: "Hội hạng A làm tối đa được bao nhiu nhiệm vụ đua thuyền?", a: "24" },
    { category: "Game Hoa Viên", q: "Thược Dược Đỏ làm nhiệm vụ đua thuyền mặc định là bao nhiu điểm", a: "23" },
    { category: "Game Hoa Viên", q: "Vạn Tuế Lá Lam làm nhiệm vụ đua thuyền mặc định được bao nhiu điểm", a: "23" },
    { category: "Game Hoa Viên", q: "Nhiệm vụ đua thuyền Bồi dưỡng hoa tươi 18 điểm là cần bồi bao nhiu cây ?", a: "2" },
    { category: "Game Hoa Viên", q: "Hội cấp 8 tối đa có bao nhiu thành viên ?", a: "37" },
    { category: "Game Hoa Viên", q: "Cần bao nhiu điểm đua thuyền để đổi 1 lần Gói thi đấu?", a: "100" },
    { category: "Game Hoa Viên", q: "Gói Thi đấu Hội hạng A mỗi lần đổi được bao nhiu vàng ?", a: "666666" },

    // ==========================================
    // 📜 NHÓM: LỊCH SỬ (30 CÂU)
    // ==========================================
    { category: "Lịch sử", q: "Vị vua nào đã dời đô về Thăng Long năm 1010?", a: "Lý Thái Tổ" },
    { category: "Lịch sử", q: "Tác giả của 'Bình Ngô Đại Cáo' là ai?", a: "Nguyễn Trãi" },
    { category: "Lịch sử", q: "Trận chiến Điện Biên Phủ trên không diễn ra vào năm nào?", a: "1972" },
    { category: "Lịch sử", q: "Ai là vị nữ vương đầu tiên trong lịch sử Việt Nam?", a: "Hai Bà Trưng" },
    { category: "Lịch sử", q: "Chiến thắng Điện Biên Phủ lừng lẫy năm nào?", a: "1954" },
    { category: "Lịch sử", q: "Vị tướng nào lãnh đạo quân Tây Sơn đánh tan 29 vạn quân Thanh?", a: "Quang Trung" },
    { category: "Lịch sử", q: "Ngô Quyền đánh tan quân Nam Hán trên sông nào năm 938?", a: "Bạch Đằng" },
    { category: "Lịch sử", q: "Ai là người đọc Bản Tuyên ngôn Độc lập ngày 2/9/1945?", a: "Hồ Chí Minh" },
    { category: "Lịch sử", q: "Triều đại phong kiến cuối cùng của Việt Nam là triều đại nào?", a: "Triều Nguyễn" },
    { category: "Lịch sử", q: "Bác Hồ ra đi tìm đường cứu nước vào năm nào?", a: "1911" },
    { category: "Lịch sử", q: "Bác Hồ ra đi tìm đường cứu nước từ bến cảng nào?", a: "Bến Nhà Rồng" },
    { category: "Lịch sử", q: "Vị vua cuối cùng của triều đại phong kiến Việt Nam là ai?", a: "Bảo Đại" },
    { category: "Lịch sử", q: "Phong trào Cần Vương do ai xướng xuất?", a: "Hàm Nghi" },
    { category: "Lịch sử", q: "Quốc hiệu đầu tiên của nước ta là gì?", a: "Văn Lang" },
    { category: "Lịch sử", q: "Người anh hùng nhỏ tuổi bóp nát quả cam vì không được dự hội nghị Bình Than là ai?", a: "Trần Quốc Toản" },
    { category: "Lịch sử", q: "Trần Hưng Đạo ba lần đánh tan quân xâm lược nào?", a: "Mông Nguyên" },
    { category: "Lịch sử", q: "Đinh Bộ Lĩnh dẹp loạn bao nhiêu sứ quân để thống nhất đất nước?", a: "12" },
    { category: "Lịch sử", q: "Phong trào Xô Viết Nghệ Tĩnh diễn ra vào năm nào?", a: "1930" },
    { category: "Lịch sử", q: "Quốc hiệu nước ta dưới thời vua Gia Long là gì?", a: "Việt Nam" },
    { category: "Lịch sử", q: "Vị vua nào là người thành lập nên nhà Tây Sơn?", a: "Nguyễn Nhạc" },
    { category: "Lịch sử", q: "Tên gọi cũ của Thành phố Hồ Chí Minh trước năm 1976 là gì?", a: "Sài Gòn" },
    { category: "Lịch sử", q: "Chiến dịch lịch sử giải phóng hoàn toàn miền Nam năm 1975 mang tên ai?", a: "Hồ Chí Minh" },
    { category: "Lịch sử", q: "Lý Thường Kiệt nổi tiếng với bài thơ thần nào?", a: "Nam quốc sơn hà" },
    { category: "Lịch sử", q: "Ai là Tổng bí thư đầu tiên của Đảng Cộng sản Việt Nam?", a: "Trần Phú" },
    { category: "Lịch sử", q: "Hiệp định Genève về chấm dứt chiến tranh ở Đông Dương được ký năm nào?", a: "1954" },
    { category: "Lịch sử", q: "Hiệp định Paris về chấm dứt chiến tranh ở Việt Nam được ký năm nào?", a: "1973" },
    { category: "Lịch sử", q: "Ai là vị tướng chỉ huy Chiến dịch Điện Biên Phủ năm 1954?", a: "Võ Nguyên Giáp" },
    { category: "Lịch sử", q: "Niên hiệu của Nguyễn Huệ sau khi lên ngôi hoàng đế là gì?", a: "Quang Trung" },
    { category: "Lịch sử", q: "Vua nào cho xây dựng Kinh thành Huế?", a: "Gia Long" },
    { category: "Lịch sử", q: "Thành Cổ Loa được xây dựng dưới thời kỳ của vị vua nào?", a: "An Dương Vương" },

    // ==========================================
    // 🗺️ NHÓM: ĐỊA LÝ (30 CÂU)
    // ==========================================
    { category: "Địa lý", q: "Dòng sông nào dài nhất thế giới?", a: "Nile" },
    { category: "Địa lý", q: "Thủ đô của Nhật Bản là gì?", a: "Tokyo" },
    { category: "Địa lý", q: "Đỉnh núi nào cao nhất thế giới?", a: "Everest" },
    { category: "Địa lý", q: "Tỉnh nào có diện tích lớn nhất Việt Nam?", a: "Nghệ An" },
    { category: "Địa lý", q: "Đảo nào có diện tích lớn nhất Việt Nam?", a: "Phú Quốc" },
    { category: "Địa lý", q: "Quốc gia nào có diện tích lớn nhất thế giới?", a: "Nga" },
    { category: "Địa lý", q: "Sông nào chảy qua thủ đô Hà Nội?", a: "Sông Hồng" },
    { category: "Địa lý", q: "Thủ đô của nước Pháp là gì?", a: "Paris" },
    { category: "Địa lý", q: "Châu lục nào có diện tích lớn nhất thế giới?", a: "Châu Á" },
    { category: "Địa lý", q: "Sa mạc nào rộng lớn nhất thế giới?", a: "Sahara" },
    { category: "Địa lý", q: "Thành phố nào là trung tâm kinh tế lớn nhất miền Nam Việt Nam?", a: "Thành phố Hồ Chí Minh" },
    { category: "Địa lý", q: "Hang động tự nhiên lớn nhất thế giới nằm ở Việt Nam tên là gì?", a: "Sơn Đoòng" },
    { category: "Địa lý", q: "Biển Hồ (Hồ T'Nưng) nằm ở tỉnh nào của Việt Nam?", a: "Gia Lai" },
    { category: "Địa lý", q: "Quốc gia nào đông dân nhất thế giới hiện nay?", a: "Ấn Độ" },
    { category: "Địa lý", q: "Thủ đô của Hàn Quốc là gì?", a: "Seoul" },
    { category: "Địa lý", q: "Vịnh biển nào của Việt Nam được UNESCO công nhận là Di sản Thiên nhiên Thế giới?", a: "Vịnh Hạ Long" },
    { category: "Địa lý", q: "Con sông nào dài nhất chảy hoàn toàn trong lãnh thổ Việt Nam?", a: "Sông Đồng Nai" },
    { category: "Địa lý", q: "Ngọn núi nào được mệnh danh là Nóc nhà Đông Dương?", a: "Fansipan" },
    { category: "Địa lý", q: "Đèo nào nối liền tỉnh Thừa Thiên Huế và thành phố Đà Nẵng?", a: "Đèo Hải Vân" },
    { category: "Địa lý", q: "Đất nước nào được mệnh danh là Xứ sở hoa anh đào?", a: "Nhật Bản" },
    { category: "Địa lý", q: "Đất nước nào có hình dáng giống như chiếc ủng trên bản đồ?", a: "Ý" },
    { category: "Địa lý", q: "Đại dương nào rộng lớn nhất trên Trái Đất?", a: "Thái Bình Dương" },
    { category: "Địa lý", q: "Hồ nước ngọt tự nhiên lớn nhất Việt Nam là hồ nào?", a: "Ba Bể" },
    { category: "Địa lý", q: "Quốc gia nào nhỏ nhất thế giới nằm hoàn toàn trong lòng thành phố Rome?", a: "Vatican" },
    { category: "Địa lý", q: "Dãy núi nào dài nhất thế giới?", a: "Andes" },
    { category: "Địa lý", q: "Đất nước nào được mệnh danh là Xứ sở kim chi?", a: "Hàn Quốc" },
    { category: "Địa lý", q: "Thành phố nào được gọi là Thành phố Ngàn hoa ở Việt Nam?", a: "Đà Lạt" },
    { category: "Địa lý", q: "Con sông nào chảy qua trung tâm thành phố Huế?", a: "Sông Hương" },
    { category: "Địa lý", q: "Đảo Greenland thuộc chủ quyền của quốc gia nào?", a: "Đan Mạch" },
    { category: "Địa lý", q: "Sông Amazon nằm chủ yếu ở châu lục nào?", a: "Châu Nam Mỹ" },

    // ==========================================
    // 📖 NHÓM: VĂN HỌC (30 CÂU)
    // ==========================================
    { category: "Văn học", q: "Tác giả của tác phẩm 'Truyện Kiều' là ai?", a: "Nguyễn Du" },
    { category: "Văn học", q: "Nhà văn nào là tác giả của tác phẩm 'Tắt đèn'?", a: "Ngô Tất Tố" },
    { category: "Văn học", q: "Làng Vũ Đại là bối cảnh trong tác phẩm nào của Nam Cao?", a: "Chí Phèo" },
    { category: "Văn học", q: "Tác giả của bài thơ 'Sóng' là ai?", a: "Xuân Quỳnh" },
    { category: "Văn học", q: "Nhân vật Mị là nhân vật chính trong tác phẩm nào của Tô Hoài?", a: "Vợ chồng A Phủ" },
    { category: "Văn học", q: "Truyện ngắn 'Làng' là tác phẩm nổi tiếng của ai?", a: "Kim Lân" },
    { category: "Văn học", q: "Bài thơ 'Đồng chí' do ai sáng tác?", a: "Chính Hữu" },
    { category: "Văn học", q: "Tác giả của tác phẩm 'Dế Mèn phiêu lưu ký' là ai?", a: "Tô Hoài" },
    { category: "Văn học", q: "Nhân vật chị Dậu xuất hiện trong tác phẩm nào?", a: "Tắt đèn" },
    { category: "Văn học", q: "Bài thơ 'Tây Tiến' do ai sáng tác?", a: "Quang Dũng" },
    { category: "Văn học", q: "Tác phẩm 'Chiếc thuyền ngoài xa' là của nhà văn nào?", a: "Nguyễn Minh Châu" },
    { category: "Văn học", q: "Ai là tác giả kịch bản 'Hồn Trương Ba, da hàng thịt'?", a: "Lưu Quang Vũ" },
    { category: "Văn học", q: "Bài thơ 'Tràng giang' do ai sáng tác?", a: "Huy Cận" },
    { category: "Văn học", q: "Tác giả của bài thơ 'Việt Bắc' là ai?", a: "Tố Hữu" },
    { category: "Văn học", q: "Tểu thuyết 'Số đỏ' do nhà văn nào sáng tác?", a: "Vũ Trọng Phụng" },
    { category: "Văn học", q: "Nhân vật Xuân Tóc Đỏ xuất hiện trong tác phẩm nào?", a: "Số đỏ" },
    { category: "Văn học", q: "Tác giả bài thơ 'Bánh trôi nước' là ai?", a: "Hồ Xuân Hương" },
    { category: "Văn học", q: "Tác giả của truyện ngắn 'Vợ nhặt' là ai?", a: "Kim Lân" },
    { category: "Văn học", q: "Ai được mệnh danh là 'Ông hoàng thơ tình' Việt Nam?", a: "Xuân Diệu" },
    { category: "Văn học", q: "Tác giả bài thơ 'Đất nước' trong trường ca 'Mặt đường khát vọng' là ai?", a: "Nguyễn Khoa Điềm" },
    { category: "Văn học", q: "Nhà văn nào viết tập tùy bút 'Sông Đà'?", a: "Nguyễn Tuân" },
    { category: "Văn học", q: "Bài thơ 'Thương vợ' do ai sáng tác?", a: "Trần Tế Xương" },
    { category: "Văn học", q: "Tác giả của tác phẩm 'Tôi thấy hoa vàng trên cỏ xanh' là ai?", a: "Nguyễn Nhật Ánh" },
    { category: "Văn học", q: "Tập thơ 'Nhật ký trong tù' do ai viết?", a: "Hồ Chí Minh" },
    { category: "Văn học", q: "Ai là tác giả bài thơ 'Đoàn thuyền đánh cá'?", a: "Huy Cận" },
    { category: "Văn học", q: "Nhân vật Lão Hạc nuôi con chó đặt tên là gì?", a: "Cậu Vàng" },
    { category: "Văn học", q: "Tác giả của truyện ngắn 'Lặng lẽ Sa Pa' là ai?", a: "Nguyễn Thành Long" },
    { category: "Văn học", q: "Nhà văn nào là tác giả của tác phẩm 'Đất rừng phương Nam'?", a: "Đoàn Giỏi" },
    { category: "Văn học", q: "Nhân vật bé Thu xuất hiện trong truyện ngắn nào của Nguyễn Quang Sáng?", a: "Chiếc lược ngà" },
    { category: "Văn học", q: "Ai sáng tác bài thơ 'Đồng chi'?", a: "Chính Hữu" },

    // ==========================================
    // 📐 NHÓM: TOÁN HỌC (30 CÂU)
    // ==========================================
    { category: "Toán học", q: "Số nguyên tố nhỏ nhất là số mấy?", a: "2" },
    { category: "Toán học", q: "Căn bậc hai của 81 bằng bao nhiêu?", a: "9" },
    { category: "Toán học", q: "Tổng các góc trong một tam giác bằng bao nhiêu độ?", a: "180" },
    { category: "Toán học", q: "Số Pi thường lấy giá trị xấp xỉ bằng bao nhiêu?", a: "3.14" },
    { category: "Toán học", q: "Một hình vuông có cạnh 5cm thì diện tích bằng bao nhiêu cm2?", a: "25" },
    { category: "Toán học", q: "Kết quả của phép tính 2 mũ 3 bằng bao nhiêu?", a: "8" },
    { category: "Toán học", q: "Tích của bất kỳ số nào với số 0 đều bằng bao nhiêu?", a: "0" },
    { category: "Toán học", q: "Số tự nhiên nhỏ nhất là số mấy?", a: "0" },
    { category: "Toán học", q: "Hình học nào có 3 cạnh?", a: "Tam giác" },
    { category: "Toán học", q: "Góc có số đo bằng 90 độ gọi là góc gì?", a: "Góc vuông" },
    { category: "Toán học", q: "Căn bậc hai của 100 bằng bao nhiêu?", a: "10" },
    { category: "Toán học", q: "Tam giác có 3 cạnh bằng nhau gọi là tam giác gì?", a: "Tam giác đều" },
    { category: "Toán học", q: "Số chẵn duy nhất là số nguyên tố là số mấy?", a: "2" },
    { category: "Toán học", q: "Tổng các góc trong một hình tứ giác bằng bao nhiêu độ?", a: "360" },
    { category: "Toán học", q: "Bội số chung nhỏ nhất của 4 và 6 là bao nhiêu?", a: "12" },
    { category: "Toán học", q: "Kết quả của phép tính 5 giai thừa (5!) bằng bao nhiêu?", a: "120" },
    { category: "Toán học", q: "Định lý Pitago áp dụng cho loại tam giác nào?", a: "Tam giác vuông" },
    { category: "Toán học", q: "Đường nối hai điểm bất kỳ trên đường tròn đi qua tâm gọi là gì?", a: "Đường kính" },
    { category: "Toán học", q: "Số đối của số 5 là số mấy?", a: "-5" },
    { category: "Toán học", q: "Căn bậc ba của 27 bằng bao nhiêu?", a: "3" },
    { category: "Toán học", q: "1 mét bằng bao nhiêu xăng-ti-mét?", a: "100" },
    { category: "Toán học", q: "Phân số 1/2 quy đổi ra phần trăm bằng bao nhiêu?", a: "50%" },
    { category: "Toán học", q: "Góc lớn hơn 0 độ và nhỏ hơn 90 độ gọi là góc gì?", a: "Góc nhọn" },
    { category: "Toán học", q: "Góc lớn hơn 90 độ và nhỏ hơn 180 độ gọi là góc gì?", a: "Góc tù" },
    { category: "Toán học", q: "Hình tròn có bao nhiêu cạnh?", a: "0" },
    { category: "Toán học", q: "Số 13 có phải là số nguyên tố không?", a: "Có" },
    { category: "Toán học", q: "Đồ thị hàm số bậc nhất y = ax + b có dạng đường gì?", a: "Đường thẳng" },
    { category: "Toán học", q: "Số dư lớn nhất trong phép chia một số cho 5 là bao nhiêu?", a: "4" },
    { category: "Toán học", q: "Kết quả của phép tính 10 chia 0.5 bằng bao nhiêu?", a: "20" },
    { category: "Toán học", q: "Hình tam giác có 1 góc vuông và 2 cạnh bằng nhau gọi là tam giác gì?", a: "Tam giác vuông cân" },

    // ==========================================
    // 🚀 NHÓM: KHOA HỌC VŨ TRỤ (30 CÂU)
    // ==========================================
    { category: "Khoa học vũ trụ", q: "Hành tinh nào gần Mặt Trời nhất?", a: "Sao Thủy" },
    { category: "Khoa học vũ trụ", q: "Hành tinh nào lớn nhất trong Hệ Mặt Trời?", a: "Sao Mộc" },
    { category: "Khoa học vũ trụ", q: "Người đầu tiên đặt chân lên Mặt Trăng là ai?", a: "Neil Armstrong" },
    { category: "Khoa học vũ trụ", q: "Trái Đất là hành tinh thứ mấy tính từ Mặt Trời?", a: "3" },
    { category: "Khoa học vũ trụ", q: "Hành tinh nào trong Hệ Mặt Trời được gọi là Hành tinh Đỏ?", a: "Sao Hỏa" },
    { category: "Khoa học vũ trụ", q: "Thiên thể nào chiếu sáng cho Trái Đất vào ban ngày?", a: "Mặt Trời" },
    { category: "Khoa học vũ trụ", q: "Tên dải ngân hà chứa Hệ Mặt Trời của chúng ta là gì?", a: "Milky Way" },
    { category: "Khoa học vũ trụ", q: "Vệ tinh tự nhiên duy nhất của Trái Đất là gì?", a: "Mặt Trăng" },
    { category: "Khoa học vũ trụ", q: "Ngôi sao nào gần Trái Đất nhất?", a: "Mặt Trời" },
    { category: "Khoa học vũ trụ", q: "Hiện tượng Trái Đất che khuất ánh sáng Mặt Trời chiếu tới Mặt Trăng gọi là gì?", a: "Nguyệt thực" },
    { category: "Khoa học vũ trụ", q: "Hiện tượng Mặt Trăng che khuất ánh sáng Mặt Trời chiếu tới Trái Đất gọi là gì?", a: "Nhật thực" },
    { category: "Khoa học vũ trụ", q: "Hành tinh nào có vành đai rõ nét và đẹp nhất trong Hệ Mặt Trời?", a: "Sao Thổ" },
    { category: "Khoa học vũ trụ", q: "Hành tinh nào lạnh nhất trong Hệ Mặt Trời?", a: "Sao Thiên Vương" },
    { category: "Khoa học vũ trụ", q: "Quốc gia đầu tiên phóng vệ tinh nhân tạo vào vũ trụ là nước nào?", a: "Liên Xô" },
    { category: "Khoa học vũ trụ", q: "Tên vệ tinh nhân tạo đầu tiên của loài người là gì?", a: "Sputnik 1" },
    { category: "Khoa học vũ trụ", q: "Người Việt Nam đầu tiên bay vào vũ trụ là ai?", a: "Phạm Tuân" },
    { category: "Khoa học vũ trụ", q: "Người đầu tiên bay vào vũ trụ là ai?", a: "Yuri Gagarin" },
    { category: "Khoa học vũ trụ", q: "Hành tinh nào nóng nhất trong Hệ Mặt Trời?", a: "Sao Kim" },
    { category: "Khoa học vũ trụ", q: "Hệ Mặt Trời có bao nhiêu hành tinh chính thức?", a: "8" },
    { category: "Khoa học vũ trụ", q: "Lực nào giữ cho các hành tinh quay quanh Mặt Trời?", a: "Lực hấp dẫn" },
    { category: "Khoa học vũ trụ", q: "Sao Kim còn được gọi bằng tên dân gian nào ở Việt Nam vào buổi sáng?", a: "Sao Mai" },
    { category: "Khoa học vũ trụ", q: "Kính thiên văn vũ trụ nổi tiếng của NASA hoạt động từ năm 1990 tên là gì?", a: "Hubble" },
    { category: "Khoa học vũ trụ", q: "Cơ quan hàng không vũ trụ Hoa Kỳ có tên viết tắt là gì?", a: "NASA" },
    { category: "Khoa học vũ trụ", q: "Năm ánh sáng là đơn vị đo chiều dài hay thời gian?", a: "Chiều dài" },
    { category: "Khoa học vũ trụ", q: "Hành tinh nào quay chậm nhất xung quanh trục của nó?", a: "Sao Kim" },
    { category: "Khoa học vũ trụ", q: "Hố đen vũ trụ có lực gì cực mạnh khiến cả ánh sáng cũng không thoát ra được?", a: "Lực hấp dẫn" },
    { category: "Khoa học vũ trụ", q: "Sao Hỏa có bao nhiêu vệ tinh tự nhiên?", a: "2" },
    { category: "Khoa học vũ trụ", q: "Mảnh đá từ vũ trụ rơi xuống bề mặt Trái Đất gọi là gì?", a: "Thiên thạch" },
    { category: "Khoa học vũ trụ", q: "Ranh giới xung quanh hố đen mà từ đó không gì thoát ra được gọi là gì?", a: "Chân trời sự kiện" },
    { category: "Khoa học vũ trụ", q: "Trái Đất tự quay quanh trục theo hướng nào?", a: "Tây sang Đông" },

    // ==========================================
    // 🧪 NHÓM: HÓA HỌC (30 CÂU)
    // ==========================================
    { category: "Hóa học", q: "Ký hiệu hóa học của Vàng là gì?", a: "Au" },
    { category: "Hóa học", q: "Công thức hóa học của nước là gì?", a: "H2O" },
    { category: "Hóa học", q: "Khí nào chiếm phần lớn thể tích không khí Trái Đất?", a: "Nitơ" },
    { category: "Hóa học", q: "Ký hiệu hóa học của Sắt là gì?", a: "Fe" },
    { category: "Hóa học", q: "Khí duy trì sự sống và sự cháy là khí gì?", a: "Ôxi" },
    { category: "Hóa học", q: "Công thức hóa học của muối ăn là gì?", a: "NaCl" },
    { category: "Hóa học", q: "Kim loại duy nhất ở trạng thái lỏng ở điều kiện thường là kim loại nào?", a: "Thủy ngân" },
    { category: "Hóa học", q: "Ký hiệu hóa học của Đồng là gì?", a: "Cu" },
    { category: "Hóa học", q: "Bảng tuần hoàn các nguyên tố hóa học do nhà khoa học nào sáng lập?", a: "Mendeleev" },
    { category: "Hóa học", q: "Dung dịch có độ pH nhỏ hơn 7 mang tính chất gì?", a: "Axit" },
    { category: "Hóa học", q: "Dung dịch có độ pH lớn hơn 7 mang tính chất gì?", a: "Bazo" },
    { category: "Hóa học", q: "Ký hiệu hóa học của Bạc là gì?", a: "Ag" },
    { category: "Hóa học", q: "Khí nào gây ra hiện tượng hiệu ứng nhà kính nhiều nhất?", a: "CO2" },
    { category: "Hóa học", q: "Nguyên tố hóa học nhẹ nhất trong bảng tuần hoàn là nguyên tố nào?", a: "Hidro" },
    { category: "Hóa học", q: "Công thức hóa học của khí Cacbonic là gì?", a: "CO2" },
    { category: "Hóa học", q: "Kim loại dẫn điện tốt nhất là kim loại nào?", a: "Bạc" },
    { category: "Hóa học", q: "Ký hiệu hóa học của Nhôm là gì?", a: "Al" },
    { category: "Hóa học", q: "Kim loại nhẹ nhất trong tất cả các kim loại là kim loại nào?", a: "Liti" },
    { category: "Hóa học", q: "Giấy quỳ tím chuyển sang màu gì khi gặp dung dịch axit?", a: "Đỏ" },
    { category: "Hóa học", q: "Giấy quỳ tím chuyển sang màu gì khi gặp dung dịch bazo?", a: "Xanh" },
    { category: "Hóa học", q: "Chất nào được mệnh danh là vua của các chất hóa học?", a: "Axit sunfuric" },
    { category: "Hóa học", q: "Nguyên tố phi kim duy nhất ở trạng thái lỏng ở điều kiện thường là gì?", a: "Brom" },
    { category: "Hóa học", q: "Ký hiệu hóa học của Ôxi là gì?", a: "O" },
    { category: "Hóa học", q: "Kim loại cứng nhất trong tất cả các kim loại là kim loại nào?", a: "Crom" },
    { category: "Hóa học", q: "Công thức hóa học của khí Mêtan là gì?", a: "CH4" },
    { category: "Hóa học", q: "Phản ứng giữa Axit và Bazo tạo ra muối và nước gọi là phản ứng gì?", a: "Trung hòa" },
    { category: "Hóa học", q: "Ký hiệu hóa học của Cacbon là gì?", a: "C" },
    { category: "Hóa học", q: "Thành phần chính của đá vôi có công thức hóa học là gì?", a: "CaCO3" },
    { category: "Hóa học", q: "Hiện tượng kim loại bị gỉ trong không khí ẩm là loại phản ứng gì?", a: "Ôxi hóa" },
    { category: "Hóa học", q: "Công thức hóa học của rượu etylic (cồn) là gì?", a: "C2H5OH" }
];

module.exports = questions;